### PR TITLE
Spacing fixes

### PR DESCRIPTION
**Pull request by pjotrp**
Massive patch set for spacing. Includes:

Some three compile time fixes for the GNU GCC 7.1.0 compiler on Linux.

### CODE REVIEW

**Comment by pcarbo** [comment]
@pjotrp Did you just run `set fileformat=unix` on all these files? Or did you do something else?

**Comment by pjotrp** [comment]
I also removed the eol spacing with sed. Please merge this one and we should be good to go.

**Comment by pjotrp** [comment]
There are compile time fixes in the second patch. They are minor.

**Comment by pcarbo** [comment]
See Issue #49 for additional details on this.

**Pull request merged**
